package likebike

/**
 * Contains information about user's role. Generated by spring security
 */
class Role {

    String authority

    static mapping = {
        cache true
    }

    static constraints = {
        authority blank: false, unique: true
    }
}
